.PHONY: clean All

All:
	@echo "----------Building project:[ Codelite - Debug ]----------"
	@cd "Codelite" && "$(MAKE)" -f  "Codelite.mk"
clean:
	@echo "----------Cleaning project:[ Codelite - Debug ]----------"
	@cd "Codelite" && "$(MAKE)" -f  "Codelite.mk" clean
